model:
  family: official_fm_unet
  hidden_channels: 128
  num_res_blocks: 4
  attention_resolutions: [2]
  dropout: 0.3
  channel_mult: [2, 2, 2]
  conv_resample: false
  dims: 2
  num_classes: null
  use_checkpoint: false
  num_heads: 1
  num_head_channels: -1
  num_heads_upsample: -1
  use_scale_shift_norm: true
  resblock_updown: false
  use_new_attention_order: true
  with_fourier_features: false
